# Generated by Django 5.0.7 on 2025-02-06 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumocirugia',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.deposito', verbose_name='Deposito Afectado'),
        ),
        migrations.AddField(
            model_name='inventariodescarga',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='Cirugia ID'),
        ),
        migrations.AddField(
            model_name='inventariodescarga',
            name='descargamanual',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='descargamanual'),
        ),
    ]
