# Generated by Django 5.0.7 on 2025-02-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0003_remove_registrodocumento_transaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='precarga',
            field=models.PositiveIntegerField(default=0, verbose_name='Precarga de medicina'),
        ),
    ]
