# Generated by Django 5.0.7 on 2025-02-13 03:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0007_inventariodescarga_cantidad_traslado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenotaentrega',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial Producto'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='unidad_conversion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unidad_conversion'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='unidadcompra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadcompra', verbose_name='unidad compra'),
        ),
        migrations.AddField(
            model_name='notaentregacompra',
            name='tasaaplicable',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='tasaaplicable'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 23, 12, 10, 178090), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
