# Generated by Django 5.0.7 on 2025-02-14 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0008_detallenotaentrega_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallenotaentrega',
            old_name='costo',
            new_name='costo_dl',
        ),
        migrations.RemoveField(
            model_name='detallenotaentrega',
            name='venta',
        ),
        migrations.AddField(
            model_name='notaentregacompra',
            name='moneda_factura',
            field=models.PositiveIntegerField(default=1, verbose_name='moneda Documento'),
        ),
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='costo_bs',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Costo Bs'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 0, 18, 34, 61398), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
