# Generated by Django 5.0.7 on 2025-02-17 00:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0010_detallenotaentrega_deposito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cedula', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Cedula')),
            ],
        ),
        migrations.RemoveField(
            model_name='detallenotaentrega',
            name='inventario_id',
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.inventario', verbose_name='Inventario'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='venta_dl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Venta usd'),
        ),
        migrations.AddField(
            model_name='notaentregacompra',
            name='cantidad_inventario_actualizado',
            field=models.BooleanField(default=False, verbose_name='cantidad_inventario_actualizado'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 20, 40, 25, 25973), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.CreateModel(
            name='InventarioHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='venta')),
                ('tasa', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='tasa')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.inventario', verbose_name='Producto')),
                ('notaentrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_entrega', to='appcc58.notaentregacompra', verbose_name='NotaEntregaCompra')),
                ('presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_entrada_his', to='appcc58.presentacionmedicina', verbose_name='Presentacion')),
                ('presentacion_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_salida_his', to='appcc58.presentacionmedicina', verbose_name='Presentacion Salida')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.proveedor', verbose_name='Proveedor')),
                ('unidadcompra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadcompra', verbose_name='unidadcompra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'InventarioHistoria',
                'verbose_name_plural': 'InventarioHistorias',
            },
        ),
    ]
