# Generated by Django 5.0.7 on 2025-02-17 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0011_imagenphoto_remove_detallenotaentrega_inventario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='costo_dl',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Costo usd'),
        ),
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='venta_dl',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Venta usd'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 11, 17, 8, 561529), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
