# Generated by Django 5.0.7 on 2025-02-19 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0015_facturaproveedor_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonocuentapagar',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='referencia pago'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='subtotal_bs',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Sub Total BS'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='subtotal_dl',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Sub Total DL'),
        ),
        migrations.AlterField(
            model_name='detallefacturaproveedor',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 2, 27, 57, 99307), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
