# Generated by Django 5.0.7 on 2025-02-20 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0016_abonocuentapagar_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 1, 0, 52, 213746), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
