# Generated by Django 5.0.7 on 2025-03-05 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0021_alter_inventario_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 20, 28, 12, 258059), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
