# Generated by Django 5.0.7 on 2025-03-12 23:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0025_consumocirugia_obligatoria_paciente_fotoperfil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='montoincremento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaquirurgica',
            name='notaeliminacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota Eliminacion'),
        ),
        migrations.AddField(
            model_name='notaquirurgica',
            name='pagoeliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 19, 25, 29, 535623), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='C:\\proyectocc58\\photos\\VU58Foto.png', null=True, upload_to='photos/'),
        ),
    ]
