# Generated by Django 5.0.7 on 2025-03-14 03:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0027_alter_inventariosolicitud_fecha_despacho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumocirugia',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='Cirugia'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 23, 47, 2, 680867), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.CreateModel(
            name='AtencionInmediata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el')),
                ('fecha_procedimiento', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Procedimiento')),
                ('motivo_atencion', models.CharField(blank=True, max_length=250, null=True, verbose_name='motivo_atencion')),
                ('dias_hospitalizacion', models.PositiveIntegerField(default=0, verbose_name='Dias Hospitaliza.')),
                ('alta_medica', models.BooleanField(default=False, verbose_name='Alta Medica')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo')),
                ('estatus', models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.estatuscirugia', verbose_name='EstatusCirugia')),
                ('medico_ppal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.medico', verbose_name='Medico Ppal')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.paciente', verbose_name='Paciente')),
                ('tipo_procedimiento', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='appcc58.tipoprocedimiento', verbose_name='Tipo Procedimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'AtencionInmediata',
                'verbose_name_plural': 'AtencionesInmediatas',
            },
        ),
        migrations.AddField(
            model_name='consumocirugia',
            name='atencion_inmediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediata', verbose_name='atencion_inmediata'),
        ),
        migrations.AddField(
            model_name='notaquirurgica',
            name='atencion_inmediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediata', verbose_name='atencion_inmediata'),
        ),
    ]
