# Generated by Django 5.0.7 on 2025-03-15 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0029_presupuesto_atencion_inmediata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 21, 49, 42, 691472), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='C:\\proyectoU58\\photos\\VU58Foto.png', null=True, upload_to='photos/'),
        ),
    ]
