# Generated by Django 5.0.7 on 2025-03-15 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0030_alter_inventariosolicitud_fecha_despacho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 21, 53, 11, 388184), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
