# Generated by Django 5.0.7 on 2025-03-25 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0036_detallecirugia_atencion_inmediata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 22, 59, 44, 128791), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
