# Generated by Django 5.0.7 on 2025-03-26 01:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0037_alter_inventariosolicitud_fecha_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecirugia',
            name='lugar_consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.lugarconsumo', verbose_name='Lugar Tratamiento'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='monto_descuento_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descuento_bs'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='lugar_consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.lugarconsumo', verbose_name='Lugar Tratamiento'),
        ),
        migrations.AddField(
            model_name='notaquirurgica',
            name='detallepresupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallepresupuesto', verbose_name='detallepresupuesto'),
        ),
        migrations.AddField(
            model_name='notaquirurgica',
            name='lugar_consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.lugarconsumo', verbose_name='Lugar Tratamiento'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='lugar_consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.lugarconsumo', verbose_name='Lugar Tratamiento'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 21, 40, 6, 963676), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
