# Generated by Django 5.0.7 on 2025-03-27 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0038_detallecirugia_lugar_consumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='costo_bs',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Costo Bs'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 22, 46, 20, 441575), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
