# Generated by Django 5.0.7 on 2025-04-04 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0043_alter_inventariosolicitud_fecha_despacho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumocirugia',
            name='advertencia',
            field=models.BooleanField(default=False, verbose_name='advertencia'),
        ),
        migrations.AddField(
            model_name='inventariodescarga',
            name='consumocirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.consumocirugia', verbose_name='consumocirugia'),
        ),
        migrations.AddField(
            model_name='notaquirurgica',
            name='usuario',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='nombre_pc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='nombre_pc'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Solicitud'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='solicitante',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depositosolicitante', to='appcc58.deposito', verbose_name='depositosolicitante'),
        ),
    ]
