# Generated by Django 5.0.7 on 2025-04-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0044_consumocirugia_advertencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='unidad_conversion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='unidad_conversion'),
        ),
    ]
