# Generated by Django 5.2 on 2025-04-23 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0048_pagomedico_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleconsumocirugia',
            name='usuario_cirugia',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cirugia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='detalleconsumocirugia',
            name='usuario_farmacia',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_farmacia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
