# Generated by Django 5.0.7 on 2025-05-17 01:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0050_detalleprefactura_detallepresupuesto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagadorUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre y Apellido')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'PagadorUnico',
                'verbose_name_plural': 'PagadoresUnicos',
            },
        ),
        migrations.RemoveField(
            model_name='detallecuentacobrar',
            name='pagador',
        ),
        migrations.RemoveField(
            model_name='inventariohistoria',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='consumocirugia',
            name='compuesto',
            field=models.CharField(choices=[('1', 'Ninguno'), ('2', 'Compuesto'), ('3', 'Suministro Bomba')], default='1', max_length=1, verbose_name='compuesto'),
        ),
        migrations.AddField(
            model_name='detallecirugia',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AddField(
            model_name='detallecuentacobrar',
            name='notacredito',
            field=models.BooleanField(default=False, verbose_name='Nota de credito aplicada'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='compuesto',
            field=models.CharField(choices=[('1', 'Ninguno'), ('2', 'Compuesto'), ('3', 'Suministro Bomba')], default='1', max_length=1, verbose_name='compuesto'),
        ),
        migrations.AddField(
            model_name='inventariohistoria',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad'),
        ),
        migrations.AddField(
            model_name='inventariohistoria',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Vence'),
        ),
        migrations.AddField(
            model_name='inventariohistoria',
            name='lote',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lote Producto'),
        ),
        migrations.AddField(
            model_name='medico',
            name='pagofrecuente',
            field=models.BooleanField(default=False, verbose_name='Pagador frecuente'),
        ),
        migrations.AddField(
            model_name='pagador',
            name='detallecuentaxcobrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallecuentacobrar', verbose_name='DetalleCuentaCobrar'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='mediomoneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.formapago', verbose_name='mediopago'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto'),
        ),
        migrations.CreateModel(
            name='InventarioCompuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad')),
                ('consumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.consumocirugia', verbose_name='consumo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'InventarioCompuesto',
                'verbose_name_plural': 'InventariosCompuestos',
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoCtaCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo')),
                ('aplicada', models.BooleanField(default=False, verbose_name='aplicada')),
                ('cuentaxcobrar_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notacredito_aplicada', to='appcc58.cuentaxcobrar', verbose_name='CuentaCobrar')),
                ('detallecuentaxcobrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notacredito_origen', to='appcc58.detallecuentacobrar', verbose_name='DetalleCuentaCobrar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('pagador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.pagadorunico', verbose_name='pagador')),
            ],
            options={
                'verbose_name': 'NotaCreditoCtaCobrar',
                'verbose_name_plural': 'NotasCreditosCtaCobrar',
            },
        ),
        migrations.CreateModel(
            name='PreIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el')),
                ('fecha_procedimiento', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Procedimiento')),
                ('hora_procedimiento', models.TimeField(null=True, verbose_name='hora ingreso')),
                ('motivo_atencion', models.CharField(blank=True, max_length=250, null=True, verbose_name='motivo_atencion')),
                ('dias_hospitalizacion', models.PositiveIntegerField(default=0, verbose_name='Dias Hospitaliza.')),
                ('alta_medica', models.BooleanField(default=False, verbose_name='Alta Medica')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo')),
                ('estatus', models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.estatuscirugia', verbose_name='EstatusCirugia')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.habitacion', verbose_name='Habitacion numero')),
                ('medico_ppal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.medico', verbose_name='Medico Ppal')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.paciente', verbose_name='Paciente')),
                ('tipo_procedimiento', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='appcc58.tipoprocedimiento', verbose_name='Tipo Procedimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'PreIngreso',
                'verbose_name_plural': 'PreIngresos',
            },
        ),
        migrations.AddField(
            model_name='notaquirurgica',
            name='preingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.preingreso', verbose_name='preingreso'),
        ),
    ]
