# Generated by Django 5.0.7 on 2025-05-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0051_pagadorunico_remove_detallecuentacobrar_pagador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_origen', models.CharField(blank=True, max_length=250, null=True, verbose_name='Cuenta')),
                ('cuenta_destino', models.CharField(blank=True, max_length=250, null=True, verbose_name='cuenta_destino')),
                ('medico_proveedor', models.CharField(blank=True, max_length=250, null=True, verbose_name='medico proveedor')),
                ('monto_bolivares', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Bolivar')),
                ('monto_dolar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Dolar')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Tasa BCV')),
                ('movimiento', models.CharField(blank=True, max_length=20, null=True, verbose_name='movimiento')),
                ('fechatransaccion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Actualizado el')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('referencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Referencia')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='username')),
                ('formapago', models.CharField(blank=True, max_length=100, null=True, verbose_name='formapago')),
                ('moneda', models.CharField(blank=True, max_length=20, null=True, verbose_name='moneda')),
                ('monto_unico', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='monto_unico')),
                ('dolares', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='dolares')),
                ('transaccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.transaccion', verbose_name='transaccion')),
            ],
            options={
                'verbose_name': 'DebitoCredito',
                'verbose_name_plural': 'DebitosCreditos',
            },
        ),
    ]
