# Generated by Django 5.0.7 on 2025-05-27 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0053_alter_debitocredito_fechatransaccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagencirugia',
            options={'verbose_name': 'ImagenCirugia', 'verbose_name_plural': 'ImagenesCirugiaS'},
        ),
        migrations.AddField(
            model_name='consumocirugia',
            name='preingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.preingreso', verbose_name='preingreso'),
        ),
        migrations.AddField(
            model_name='cuentaxcobrar',
            name='preingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.preingreso', verbose_name='preingreso'),
        ),
        migrations.AddField(
            model_name='imagencirugia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='inventariodescarga',
            name='preingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.preingreso', verbose_name='preingreso'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='preingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.preingreso', verbose_name='preingreso'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='preingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.preingreso', verbose_name='preingreso'),
        ),
        migrations.AlterField(
            model_name='debitocredito',
            name='fechatransaccion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
