# Generated by Django 5.0.7 on 2025-05-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0054_alter_imagencirugia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleconsumocirugia',
            name='nota',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nota'),
        ),
    ]
