# Generated by Django 5.0.7 on 2025-06-11 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0055_detalleconsumocirugia_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preingreso',
            name='alta_medica',
        ),
        migrations.RemoveField(
            model_name='preingreso',
            name='dias_hospitalizacion',
        ),
        migrations.RemoveField(
            model_name='preingreso',
            name='fecha_procedimiento',
        ),
        migrations.RemoveField(
            model_name='preingreso',
            name='hora_procedimiento',
        ),
        migrations.RemoveField(
            model_name='preingreso',
            name='medico_ppal',
        ),
        migrations.RemoveField(
            model_name='preingreso',
            name='motivo_atencion',
        ),
        migrations.RemoveField(
            model_name='preingreso',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='preingreso',
            name='tipo_procedimiento',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='preingreso',
        ),
        migrations.AddField(
            model_name='detallebaremo',
            name='preingreso',
            field=models.BooleanField(default=False, verbose_name='preingreso'),
        ),
        migrations.AddField(
            model_name='detallecirugia',
            name='modificacion_cerrado',
            field=models.BooleanField(default=False, verbose_name='modificacion_cerrado'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='modificacion_cerrado',
            field=models.BooleanField(default=False, verbose_name='modificacion_cerrado'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='preingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.preingreso', verbose_name='preingreso'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='cirugia'),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='codigo',
            field=models.CharField(max_length=15, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.habitacion', verbose_name='habitacion'),
        ),
    ]
