# Generated by Django 5.0.7 on 2025-07-02 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0056_remove_preingreso_alta_medica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenotaentrega',
            name='marca',
            field=models.BooleanField(default=False, verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='notaentregacompra',
            name='marca',
            field=models.BooleanField(default=False, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.convenio', verbose_name='Convenio'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='estatus',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.estatuscirugia', verbose_name='EstatusCirugia'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='medico_ppal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.medico', verbose_name='Medico Ppal'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='presupuesto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.presupuesto', verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='quirofano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.quirofano', verbose_name='No. Quirofano'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='tipo_procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.tipoprocedimiento', verbose_name='Tipo Procedimiento'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='consumocirugia',
            name='cantidad_real_usada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_real_usada'),
        ),
        migrations.AlterField(
            model_name='consumocirugia',
            name='cantidad_uso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_uso'),
        ),
        migrations.AlterField(
            model_name='detalleconsumocirugia',
            name='cantidad_uso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_uso'),
        ),
        migrations.AlterField(
            model_name='inventariodescarga',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='inventariodescarga',
            name='cantidad_traslado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_traslado'),
        ),
        migrations.AlterField(
            model_name='origenpago',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='atencion_inmediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.atencioninmediata', verbose_name='atencion_inmediata'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.convenio', verbose_name='Convenio'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='estatus',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.estatuscirugia', verbose_name='EstatusCirugia'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='medico_ppal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.medico', verbose_name='Medico Ppal'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.responsable', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='tipo_procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.tipoprocedimiento', verbose_name='Tipo Procedimiento'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
