# Generated by Django 5.0.7 on 2025-07-03 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0057_detallenotaentrega_marca_notaentregacompra_marca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='ultimo_estatus',
            field=models.PositiveIntegerField(default=None, verbose_name='ultimo_estatus'),
        ),
        migrations.CreateModel(
            name='LogCuentaCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_bs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto_bs')),
                ('monto_dl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto_dl')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('nota', models.CharField(blank=True, default='Eliminacion de Pago en cuenta x cobrar', max_length=200, null=True, verbose_name='nota')),
                ('ami', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.atencioninmediata', verbose_name='Ami ID')),
                ('cirugia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.cirugia', verbose_name='Cirugia ID')),
                ('preingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.preingreso', verbose_name='Preingreso ID')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.presupuesto', verbose_name='presupuesto ID')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'LogCuentaCobrar',
                'verbose_name_plural': 'LogsCuentasCobrar',
            },
        ),
    ]
