# Generated by Django 5.0.7 on 2025-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0058_cirugia_ultimo_estatus_logcuentacobrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugia',
            name='ultimo_estatus',
            field=models.PositiveIntegerField(default=7, verbose_name='ultimo_estatus'),
        ),
    ]
