# Generated by Django 5.0.7 on 2025-07-22 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0063_numeracionfactura_debitocredito_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumocirugia',
            name='hora',
            field=models.TimeField(default=datetime.time(23, 31, 40, 961724), null=True, verbose_name='Hora asignacion'),
        ),
    ]
