# Generated by Django 5.0.7 on 2025-07-28 00:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0064_alter_consumocirugia_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitocredito',
            name='notacredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.notacreditoctacobrar', verbose_name='notacredito'),
        ),
        migrations.AddField(
            model_name='notacreditoctacobrar',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion pago'),
        ),
        migrations.AddField(
            model_name='notacreditoctacobrar',
            name='fechatasa',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha tasa bcv'),
        ),
        migrations.AddField(
            model_name='notacreditoctacobrar',
            name='presupuesto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.presupuesto', verbose_name='presupuesto_referencia'),
        ),
        migrations.AddField(
            model_name='notacreditoctacobrar',
            name='saldo_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='saldo_bs'),
        ),
        migrations.AddField(
            model_name='notacreditoctacobrar',
            name='tasa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='tasa'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='notacredito',
            field=models.PositiveIntegerField(default=0, verbose_name='id notacredito'),
        ),
        migrations.AlterField(
            model_name='consumocirugia',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 43, 39, 750501), null=True, verbose_name='Hora asignacion'),
        ),
        migrations.AlterField(
            model_name='debitocredito',
            name='motivo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='motivo'),
        ),
    ]
