# Generated by Django 5.0.7 on 2025-07-29 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0065_debitocredito_notacredito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preingreso',
            name='nombre_procedimiento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Procedimiento'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='nota',
            field=models.CharField(blank=True, max_length=200, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='consumocirugia',
            name='hora',
            field=models.TimeField(default=datetime.time(21, 10, 12, 185820), null=True, verbose_name='Hora asignacion'),
        ),
    ]
