# Generated by Django 5.0.7 on 2025-07-30 02:21

import appcc58.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0066_preingreso_nombre_procedimiento_presupuesto_nota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaxcobrar',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='consumocirugia',
            name='hora',
            field=models.TimeField(default=appcc58.models.get_current_time, null=True, verbose_name='Hora asignacion'),
        ),
    ]
