# Generated by Django 5.0.7 on 2025-08-05 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0067_cuentaxcobrar_usuario_alter_consumocirugia_hora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreSubBaremo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'NombreSubBaremo',
                'verbose_name_plural': 'Nombre SubBaremos',
            },
        ),
        migrations.AddField(
            model_name='baremo',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AddField(
            model_name='baremo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='consumocirugia',
            name='detalle_presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallepresupuesto', verbose_name='DetallePresupuesto'),
        ),
        migrations.AddField(
            model_name='detallebaremo',
            name='activar_subbaremo',
            field=models.BooleanField(default=False, verbose_name='activar_subbaremo'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='baremo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.baremo', verbose_name='Baremo'),
        ),
        migrations.AddField(
            model_name='subdetallebaremo',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AddField(
            model_name='subdetallebaremo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='estatus',
            field=models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.estatuscirugia', verbose_name='EstatusCirugia'),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.habitacion', verbose_name='habitacion'),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='SubBaremo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallebaremo', verbose_name='DetalleBaremo')),
                ('nombre_subbaremo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.nombresubbaremo', verbose_name='nombre_subbaremo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'SubBaremo',
                'verbose_name_plural': 'SubBaremos Baremos',
            },
        ),
        migrations.CreateModel(
            name='DetalleSubBaremoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cantidad')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('cirugia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='cirugia')),
                ('detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallebaremo', verbose_name='DetalleBaremo')),
                ('detalle_presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallepresupuesto', verbose_name='detalle_presupuesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('subbaremo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.subbaremo', verbose_name='SubBaremo')),
            ],
            options={
                'verbose_name': 'DetalleSubBaremoConsumo',
                'verbose_name_plural': 'DetalleSubBaremoConsumos Baremos',
            },
        ),
    ]
