# Generated by Django 5.0.7 on 2025-08-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0069_altamedica_usuario_cirugia_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecuentacobrar',
            name='montocobrar_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='monto cobrar BS'),
        ),
    ]
