# Generated by Django 5.0.7 on 2025-08-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0070_alter_detallecuentacobrar_montocobrar_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancolocal',
            name='alias',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='alias'),
        ),
    ]
