# Generated by Django 5.0.7 on 2025-08-23 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0072_detallecuentacobrar_notacredito_manual_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonocuentapagar',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA_PAGO'),
        ),
        migrations.AddField(
            model_name='bancolocal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='formapagoproveedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='formapagoproveedor',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AddField(
            model_name='formapagoproveedor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='abonocuentapagar',
            name='destino_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.formapagoproveedor', verbose_name='Destino Pago'),
        ),
    ]
