# Generated by Django 5.0.7 on 2025-08-24 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0073_abonocuentapagar_fecha_pago_bancolocal_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='porcentaje_retencion',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=10, verbose_name='% Retencion IVA'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='tipoproveedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='tipoproveedor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='descripcion de tipo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipoproveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.tipoproveedor', verbose_name='Tipo Proveedor'),
        ),
        migrations.AlterField(
            model_name='tipoproveedor',
            name='nombre',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Nombre de tipo'),
            preserve_default=False,
        ),
    ]
