# Generated by Django 5.0.7 on 2025-08-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0074_proveedor_activo_proveedor_porcentaje_retencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='porcentaje_retencion_islr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='porcentaje_retencion_islr'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto_activo',
            field=models.BooleanField(default=True, verbose_name='producto_activo'),
        ),
    ]
