# Generated by Django 5.0.7 on 2025-08-28 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0075_facturaproveedor_porcentaje_retencion_islr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremoVinculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('detalle_baremo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_baremo', to='appcc58.detallebaremo', verbose_name='detalle_baremo')),
                ('detalle_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_principal', to='appcc58.detallebaremo', verbose_name='detalle_principal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'BaremoVinculado',
                'verbose_name_plural': 'BaremosVinculados ',
            },
        ),
    ]
