# Generated by Django 5.0.7 on 2025-09-04 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0078_numeracionfactura_cirugia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePrefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cantidad')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cantidad usada')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('precio_usado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Usado')),
                ('notas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notas')),
                ('tx', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tasa')),
                ('ntqx', models.BooleanField(default=False, verbose_name='Nota Quirurgica')),
                ('montotope', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Tope')),
                ('montoconsumo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Consumo')),
                ('excedente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Excedente')),
                ('alertaexcedente', models.BooleanField(default=True, verbose_name='Alertar Excedentes')),
                ('precio_congelado_cirugia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Congelado Cirugia')),
                ('precio_congelado_presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Congelado Presupuesto')),
                ('precio_congelado_excedente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Congelado excedente')),
                ('grupo_factura', models.PositiveIntegerField(default=0, verbose_name='grupo_factura')),
                ('fecha_act', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.convenio', verbose_name='Convenio')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.detallebaremo', verbose_name='Detalle')),
                ('detallepresupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallepresupuesto', verbose_name='Detalle de Presupuesto')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.numeracionfactura', verbose_name='factura')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.grupobaremo', verbose_name='Grupo Baremo')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.medico', verbose_name='Medico')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.plantilla', verbose_name='Plantilla')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.unidad', verbose_name='Unidad Baremo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'DetallePrefactura',
                'verbose_name_plural': 'DetallesPrefactura',
            },
        ),
    ]
