# Generated by Django 5.0.7 on 2025-10-24 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0082_detallefacturaproveedor_deposito_carga_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumocirugia',
            name='precio_costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio_costo_unitario'),
        ),
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='costo_bs',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Costo Bs'),
        ),
        migrations.CreateModel(
            name='MateriaPrimaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=200, null=True, verbose_name='nota')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cantidad')),
                ('precio_dl', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='precio_dl')),
                ('subtotal_precio_dl', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='subtotal_precio_dl')),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.deposito', verbose_name='deposito')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_prima', to='appcc58.inventario', verbose_name='materia_prima')),
                ('producto_terminado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_terminado', to='appcc58.inventario', verbose_name='producto_terminado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'MateriaPrimaInventario',
                'verbose_name_plural': 'Materias Primas Inventarios',
            },
        ),
        migrations.AddField(
            model_name='inventariodescarga',
            name='materiaprima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.materiaprimainventario', verbose_name='materiaprima'),
        ),
    ]
