# Generated by Django 5.0.7 on 2025-10-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0083_consumocirugia_precio_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumocirugia',
            name='fecha_act',
            field=models.DateTimeField(null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
