# Generated by Django 5.0.7 on 2025-11-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0091_detallefacturaproveedor_montoiva_dl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(max_length=250, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='nota',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nota del Pago'),
        ),
    ]
