# Generated by Django 5.0.7 on 2025-11-25 03:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0092_alter_transaccion_descripcion_alter_transaccion_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionInmediataCortesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('fecha_procedimiento', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Procedimiento')),
                ('hora_procedimiento', models.TimeField(null=True, verbose_name='hora ingreso')),
                ('motivo_atencion', models.CharField(blank=True, max_length=250, null=True, verbose_name='motivo_atencion')),
                ('dias_hospitalizacion', models.PositiveIntegerField(default=0, verbose_name='Dias Hospitaliza.')),
                ('alta_medica', models.BooleanField(default=False, verbose_name='Alta Medica')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo')),
                ('estatus', models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.estatuscirugia', verbose_name='EstatusCirugia')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.habitacion', verbose_name='Habitacion numero')),
                ('medico_ppal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.medico', verbose_name='Medico Ppal')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.paciente', verbose_name='Paciente')),
                ('tipo_procedimiento', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='appcc58.tipoprocedimiento', verbose_name='Tipo Procedimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'AtencionInmediataCortesia',
                'verbose_name_plural': 'AtencionInmediatasCortesias',
            },
        ),
    ]
