# Generated by Django 5.0.7 on 2026-01-30 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0098_detallepresupuesto_monto_descuento_pr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='numerocontrol',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero control'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='numerodocumento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero Documento'),
        ),
        migrations.AlterField(
            model_name='notaentregacompra',
            name='numerodocumento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero Documento'),
        ),
        migrations.CreateModel(
            name='HistoriaTransOperatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='fecha_inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='fecha_fin')),
                ('inicio_cronometro_1', models.DateTimeField(blank=True, null=True, verbose_name='inicio_cronometro_1')),
                ('inicio_cronometro_2', models.DateTimeField(blank=True, null=True, verbose_name='inicio_cronometro_2')),
                ('inicio_cronometro_3', models.DateTimeField(blank=True, null=True, verbose_name='inicio_cronometro_3')),
                ('nombre_cronometro_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre_cronometro_1')),
                ('nombre_cronometro_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre_cronometro_2')),
                ('nombre_cronometro_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='nombre_cronometro_3')),
                ('tiempo_cronometro_1', models.DurationField(blank=True, null=True)),
                ('tiempo_cronometro_2', models.DurationField(blank=True, null=True)),
                ('tiempo_cronometro_3', models.DurationField(blank=True, null=True)),
                ('nota_enfermeria', models.TextField(blank=True, null=True, verbose_name='nota_enfermeria')),
                ('nota_cirugia', models.TextField(blank=True, null=True, verbose_name='nota_cirugia')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('finalizada', models.BooleanField(default=False, verbose_name='finalizada')),
                ('actualizar', models.BooleanField(default=False, verbose_name='actualizar')),
                ('cirugia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='cirugia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'HistoriaTransOperatoria',
                'verbose_name_plural': 'HistoriaTransOperatorias',
            },
        ),
    ]
