# Generated by Django 5.0.7 on 2026-02-06 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0100_abonocuentapagar_factura_pago_multiple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonocuentapagar',
            name='nota_credito',
            field=models.BooleanField(default=False, verbose_name='nota_credito'),
        ),
        migrations.AddField(
            model_name='abonocuentapagar',
            name='nota_credito_generada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_generada', to='appcc58.facturaproveedor', verbose_name='nota_credito_generada pagar'),
        ),
    ]
