# Generated by Django 5.0.7 on 2026-02-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0101_abonocuentapagar_nota_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonocuentapagar',
            name='igtf',
            field=models.BooleanField(default=False, verbose_name='igtf'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='igtf',
            field=models.BooleanField(default=False, verbose_name='igtf'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nombre Diagnostico'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='nombre_procedimiento',
            field=models.CharField(max_length=500, verbose_name='Nombre Procedimiento'),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='nombre_procedimiento',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre Procedimiento'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nombre Diagnostico'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='nombre_procedimiento',
            field=models.CharField(max_length=500, verbose_name='Nombre Procedimiento'),
        ),
    ]
