# Generated by Django 5.0.7 on 2026-03-11 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0102_abonocuentapagar_igtf_facturaproveedor_igtf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReutilizacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cantidad')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('cirugia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='cirugia')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcc58.inventario', verbose_name='inventario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'ReutilizacionInventario',
                'verbose_name_plural': 'ReutilizacionesInventarios',
            },
        ),
    ]
