# Generated by Django 5.0.7 on 2026-03-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0106_notaentregacompra_convertida_factura_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='no_inventario',
            field=models.BooleanField(default=False, verbose_name='no_inventario'),
        ),
    ]
