# Generated by Django 5.0.7 on 2026-03-25 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0107_detallefacturaproveedor_no_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultapreanestesia',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_anestesia/', verbose_name='Firma del Paciente'),
        ),
        migrations.AddField(
            model_name='inventariodescarga',
            name='reciclado',
            field=models.BooleanField(default=False, verbose_name='reciclado'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='activo_factura_medico',
            field=models.BooleanField(default=True, verbose_name='activo_factura_medico'),
        ),
        migrations.AlterField(
            model_name='detallefacturaproveedor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion'),
        ),
        migrations.CreateModel(
            name='DistribucionPagoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='monto')),
                ('tipo', models.CharField(default='PGO', max_length=3, verbose_name='tipo')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.facturaproveedor', verbose_name='factura')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.moneda', verbose_name='moneda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'DistribucionPagoMedico',
                'verbose_name_plural': 'DistribucionPagoMedicos',
            },
        ),
    ]
