# Generated by Django 5.0.7 on 2026-03-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0109_remove_facturamedico_baseimponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='reusable',
            field=models.BooleanField(default=False, verbose_name='reusable'),
        ),
    ]
