# Generated by Django 5.0.7 on 2026-03-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0110_inventario_reusable'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultapreanestesia',
            name='leucosito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='leucosito'),
        ),
    ]
