# Generated by Django 5.0.7 on 2026-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0114_alter_medico_fotoperfil_alter_paciente_fotoperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='centro_costo',
        ),
        migrations.RemoveField(
            model_name='unidadcompra',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='presentacionmedicina',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='nueva_clasificacion',
        ),
        migrations.RemoveField(
            model_name='detallenotaentrega',
            name='clasificacion',
        ),
        migrations.AlterModelOptions(
            name='unidadcompra',
            options={'verbose_name': 'UnidadCompra', 'verbose_name_plural': 'UnidadCompra de Inventarios'},
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='nueva_categoria',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='nueva_fechaelaboracion',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='nueva_fechavencimiento',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='nueva_presentacion_salida',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='nueva_unidadcompra',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='nuevo_laboratorio',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='nuevo_lote',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='nuevo_nombre_comercial',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='precio_unico_factor_dl',
        ),
        migrations.RemoveField(
            model_name='detallefacturaproveedor',
            name='unidades_con_factor',
        ),
        migrations.RemoveField(
            model_name='inventariohistoria',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='inventariohistoria',
            name='factura_compra',
        ),
        migrations.RemoveField(
            model_name='inventariohistoria',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='inventariohistoria',
            name='piva',
        ),
        migrations.RemoveField(
            model_name='presentacionmedicina',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='presentacionmedicina',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='unidadcompra',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='unidadcompra',
            name='cantidad_bulto',
        ),
        migrations.RemoveField(
            model_name='unidadcompra',
            name='cantidad_unidad_bulto',
        ),
        migrations.AlterField(
            model_name='medico',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='C:/proyectoU58/photos/MedicoU58.png', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='C:/proyectoU58/photos/VU58Foto.png', null=True, upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='CentroCostoFacturaCompra',
        ),
        migrations.DeleteModel(
            name='UnidadProducto',
        ),
    ]
