# Generated by Django 5.0.14 on 2026-04-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0117_baremopagotercero'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='baremo_pago_tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.baremopagotercero', verbose_name='baremo_pago_tercero'),
        ),
    ]
