# Generated by Django 5.0.14 on 2026-04-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0118_detallefacturaproveedor_baremo_pago_tercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baremopagotercero',
            name='nombre',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
