# Generated by Django 5.0.14 on 2026-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0119_alter_baremopagotercero_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baremopagotercero',
            name='precio',
        ),
        migrations.AddField(
            model_name='baremopagotercero',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
