# Generated by Django 5.0.14 on 2026-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0123_rename_actualizado_baremopagotercero_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nc',
            field=models.BooleanField(default=False, verbose_name='nota credito'),
        ),
    ]
