# Generated by Django 5.0.14 on 2026-05-06 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0125_historianotacreditocc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historianotacreditocc',
            old_name='saldo',
            new_name='monto_aplicado_dl',
        ),
        migrations.RemoveField(
            model_name='historianotacreditocc',
            name='saldo_bs',
        ),
        migrations.AddField(
            model_name='historianotacreditocc',
            name='monto_aplicado_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='saldo_bs'),
        ),
        migrations.AlterField(
            model_name='historianotacreditocc',
            name='notacredito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='appcc58.notacreditoctacobrar', verbose_name='nota credito padre'),
        ),
    ]
