# Generated by Django 5.0.14 on 2026-05-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0126_rename_saldo_historianotacreditocc_monto_aplicado_dl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historianotacreditocc',
            name='pagador',
        ),
    ]
