# Generated by Django 5.0.14 on 2026-05-14 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0127_remove_historianotacreditocc_pagador'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditoctacobrar',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.formapago', verbose_name='forma_pago'),
        ),
    ]
