# Generated by Django 5.0.14 on 2026-05-17 00:16

import appcc58.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0130_modulosistema_opcionespecificamodulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudsoporte',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Solicitud de Soporte', 'verbose_name_plural': 'Solicitudes de Soporte'},
        ),
        migrations.RemoveField(
            model_name='solicitudsoporte',
            name='atendido',
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='comentarios_tecnicos',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Equipo de Soporte'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_progreso', 'En Progreso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20, verbose_name='Estado del Ticket'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='prioridad_interna',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridad Interna'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=appcc58.models.ruta_adjuntos_soporte, verbose_name='Archivo Adjunto'),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte'),
        ),
    ]
