# Generated by Django 5.0.14 on 2026-05-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0131_alter_solicitudsoporte_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de reporte'),
        ),
    ]
