# Generated by Django 5.0.14 on 2026-05-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0132_alter_solicitudsoporte_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsoporte',
            name='fecha_estimada_culminacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de culminación'),
        ),
    ]
