# Generated by Django 5.0.14 on 2026-05-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0133_solicitudsoporte_fecha_estimada_culminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='prioridad_interna',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10, null=True, verbose_name='Prioridad Interna'),
        ),
    ]
