# Generated by Django 5.0.14 on 2026-05-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0134_alter_solicitudsoporte_prioridad_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaquirurgica',
            name='excepcion_pago',
            field=models.BooleanField(default=False, verbose_name='excepcion_pago'),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='prioridad_interna',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=15, null=True, verbose_name='Prioridad Interna'),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='tipo_solicitud',
            field=models.CharField(choices=[('bug', 'Reportar un Error o mal funcionamiento'), ('mejora', 'Aplicar una Mejora a modulo existente'), ('soporte', 'Duda de Usuario'), ('nueva', 'Nueva opcion, modulo o funcionalidad')], max_length=20, verbose_name='Tipo de solicitud'),
        ),
    ]
