# Generated by Django 5.0.14 on 2026-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0139_alter_consultapreanestesia_hiv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultapreanestesia',
            name='ta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ta'),
        ),
    ]
