# Generated by Django 5.0.14 on 2026-06-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0141_detallefacturaproveedor_detalle_origen_prefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='preingreso',
            name='fecha_procedimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Procedimiento'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='hora_procedimiento',
            field=models.TimeField(null=True),
        ),
    ]
