# Generated by Django 5.0.14 on 2026-06-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0142_preingreso_fecha_procedimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultapreanestesia',
            name='imc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='imc'),
        ),
    ]
