# Generated by Django 5.0.14 on 2026-06-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0143_alter_consultapreanestesia_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultapreanestesia',
            name='spo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='spo'),
        ),
        migrations.AddField(
            model_name='consultapreanestesia',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='temperatura'),
        ),
        migrations.AlterField(
            model_name='consultapreanestesia',
            name='imc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='imc'),
        ),
    ]
