# Generated by Django 5.0.14 on 2026-06-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0146_alter_transaccion_cuentapagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='siglas',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Siglas'),
        ),
    ]
