# Generated by Django 5.0.14 on 2026-06-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0149_notacreditoctapagar_historianotacreditocp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historianotacreditocp',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='notacreditoctapagar',
            name='forma_pago',
        ),
        migrations.AddField(
            model_name='historianotacreditocp',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.facturaproveedor', verbose_name='factura'),
        ),
        migrations.AddField(
            model_name='notacreditoctapagar',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.facturaproveedor', verbose_name='factura'),
        ),
    ]
