# Generated by Django 5.0.14 on 2026-06-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0150_remove_historianotacreditocp_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historianotacreditocp',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_pago'),
        ),
        migrations.AddField(
            model_name='notacreditoctapagar',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.formapago', verbose_name='forma_pago'),
        ),
    ]
