# Generated by Django 5.0.14 on 2026-06-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0152_remove_historianotacreditocp_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugia',
            name='fecha_creacion',
        ),
    ]
