# Generated by Django 5.0.14 on 2026-06-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0153_remove_cirugia_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirugia',
            name='uci',
        ),
    ]
