# Generated by Django 5.0.14 on 2026-06-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0154_remove_cirugia_uci'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='cierre_caso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cierre_caso'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_creacion'),
        ),
    ]
