# Generated by Django 5.0.14 on 2026-06-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0155_cirugia_cierre_caso_cirugia_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='prefactura_consolidada',
            field=models.BooleanField(default=False, verbose_name='prefactura_consolidada'),
        ),
    ]
