# Generated by Django 5.0.14 on 2026-06-13 00:52

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0156_facturaproveedor_prefactura_consolidada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, default='codxxx', max_length=20, verbose_name='Codigo Producto')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Producto')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial Producto')),
                ('lote', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lote Producto')),
                ('cantidad_unitaria', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_unitaria')),
                ('unidad_conversion', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='unidad_conversion')),
                ('capacidadunidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='capacidadunidad')),
                ('cantidad_max', models.PositiveBigIntegerField(default=0, verbose_name='Cantidad Maxima')),
                ('cantidad_kit', models.PositiveBigIntegerField(default=1, verbose_name='Cantidad Kit')),
                ('cantidad_min', models.PositiveBigIntegerField(default=0, verbose_name='Cantidad Minima')),
                ('cantidad_cri', models.PositiveBigIntegerField(default=0, verbose_name='Cantidad Critica')),
                ('fecha_elaboracion', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Ingreso')),
                ('fecha_vencimiento', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Vence')),
                ('fecha_act', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha Actualizacion')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='venta')),
                ('piva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% IVA')),
                ('venta_kit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Venta en KIT')),
                ('cantidad_total_usada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_total_usada')),
                ('compuesto', models.CharField(choices=[('1', 'Ninguno'), ('2', 'Compuesto'), ('3', 'Suministro Bomba')], default='1', max_length=1, verbose_name='compuesto')),
                ('producto_activo', models.BooleanField(default=True, verbose_name='producto_activo')),
                ('reusable', models.BooleanField(default=False, verbose_name='reusable')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.categoriainventario', verbose_name='Categoria')),
                ('clasificacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.unidadproducto', verbose_name='unidad')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incremento', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.montoincremento', verbose_name='incremento')),
                ('kit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.kitinventario', verbose_name='Pertenece a Kit')),
                ('laboratorio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.laboratoriomedicina', verbose_name='Laboratorio')),
                ('presentacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.presentacionmedicina', verbose_name='Presentacion')),
                ('presentacion_salida', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.presentacionmedicina', verbose_name='Presentacion Salida')),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.proveedor', verbose_name='Proveedor')),
                ('unidadcompra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.unidadcompra', verbose_name='unidadcompra')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Inventario',
                'verbose_name_plural': 'historical Inventarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
