# Generated by Django 5.0.7 on 2025-02-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0002_consumocirugia_deposito_inventariodescarga_cirugia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodocumento',
            name='transaccion',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='registro_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.registrodocumento', verbose_name='RegistroDocumento'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='bancolocal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.bancolocal', verbose_name='Banco Local'),
        ),
    ]
