# Generated by Django 5.0.7 on 2025-02-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0004_cirugia_precarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='precarga',
            field=models.BooleanField(default=False, verbose_name='Precarga de Qx'),
        ),
    ]
