# Generated by Django 5.0.7 on 2025-02-11 03:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0005_deposito_precarga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariodescarga',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.medico', verbose_name='Persona entrega'),
        ),
        migrations.AddField(
            model_name='tipodescarga',
            name='solicitud',
            field=models.BooleanField(default=False, verbose_name='solicitud'),
        ),
        migrations.CreateModel(
            name='InventarioSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad')),
                ('fecha_solicitud', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('fecha_despacho', models.DateTimeField(default=datetime.datetime(2025, 2, 10, 23, 13, 52, 828857), null=True, verbose_name='Fecha Actualizacion')),
                ('pendiente', models.BooleanField(default=True, verbose_name='Apendiente')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.inventario', verbose_name='Inventario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'InventarioSolicitud',
                'verbose_name_plural': 'InventarioSolicitudes',
            },
        ),
    ]
