# Generated by Django 5.0.7 on 2025-02-12 05:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0006_inventariodescarga_persona_tipodescarga_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariodescarga',
            name='cantidad_traslado',
            field=models.PositiveBigIntegerField(default=0, verbose_name='cantidad_traslado'),
        ),
        migrations.AddField(
            model_name='inventariosolicitud',
            name='depositoorigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.deposito', verbose_name='depositoorigen'),
        ),
        migrations.AddField(
            model_name='inventariosolicitud',
            name='existenciaorigen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='existenciaorigen'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 1, 14, 14, 230554), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
