# Generated by Django 5.0.7 on 2025-02-15 03:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0009_rename_costo_detallenotaentrega_costo_dl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenotaentrega',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.deposito', verbose_name='deposito'),
        ),
        migrations.AlterField(
            model_name='depositouso',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='appcc58.inventario', verbose_name='Producto de Inventario'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 23, 16, 32, 351647), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
