# Generated by Django 5.0.7 on 2025-02-17 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0012_alter_detallenotaentrega_costo_dl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenotaentrega',
            name='cambioaplicado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='cambioaplicado'),
        ),
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='costo_bs',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Costo Bs'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 15, 24, 39, 166685), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
