# Generated by Django 5.0.7 on 2025-02-18 03:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0013_detallenotaentrega_cambioaplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='detallenotaentrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallenotaentrega', verbose_name='detallenotaentrega'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='notaentrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.notaentregacompra', verbose_name='NotaEntregaCompra'),
        ),
        migrations.AddField(
            model_name='notaentregacompra',
            name='convertida_factura',
            field=models.BooleanField(default=False, verbose_name='convertida_factura'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 23, 45, 58, 426027), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AlterField(
            model_name='tipodescarga',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='descripcion'),
        ),
    ]
