# Generated by Django 5.0.7 on 2025-02-22 02:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0017_alter_inventariosolicitud_fecha_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='monto_descuento_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto_descuento_bs'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='incremento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appcc58.montoincremento', verbose_name='incremento'),
        ),
        migrations.AddField(
            model_name='inventariosolicitud',
            name='solicitante',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depositosolicitante', to='appcc58.deposito', verbose_name='depositoorigen'),
        ),
        migrations.AddField(
            model_name='notaentregacompra',
            name='monto_descuento_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto_descuento_bs'),
        ),
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='costo_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Bs'),
        ),
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='costo_dl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo usd'),
        ),
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='venta_dl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Venta usd'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='depositoorigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depositoorigen', to='appcc58.deposito', verbose_name='depositoorigen'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 22, 28, 42, 652387), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
