# Generated by Django 5.0.7 on 2025-02-24 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0018_facturaproveedor_monto_descuento_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='porcentaje_descuento'),
        ),
        migrations.AddField(
            model_name='notaentregacompra',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='porcentaje_descuento'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 21, 0, 52, 86831), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
