# Generated by Django 5.0.7 on 2025-02-26 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0019_facturaproveedor_porcentaje_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='precio_dl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Dl'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='actualizada',
            field=models.BooleanField(default=False, verbose_name='actualizada'),
        ),
        migrations.AlterField(
            model_name='detallefacturaproveedor',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='detallefacturaproveedor',
            name='subtotal_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sub Total BS'),
        ),
        migrations.AlterField(
            model_name='detallefacturaproveedor',
            name='subtotal_dl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sub Total DL'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 23, 37, 50, 801950), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
