# Generated by Django 5.0.7 on 2025-02-27 03:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0020_detallefacturaproveedor_precio_dl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.kitinventario', verbose_name='Pertenece a Kit'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 23, 14, 12, 667451), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
