# Generated by Django 5.0.7 on 2025-03-06 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0022_alter_inventariosolicitud_fecha_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugia',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Diagnostico'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='nombre_procedimiento',
            field=models.CharField(max_length=200, verbose_name='Nombre Procedimiento'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 22, 42, 21, 622878), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Diagnostico'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='nombre_procedimiento',
            field=models.CharField(max_length=200, verbose_name='Nombre Procedimiento'),
        ),
    ]
