# Generated by Django 5.0.7 on 2025-03-07 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0023_alter_cirugia_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugia',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre Diagnostico'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='nombre_procedimiento',
            field=models.CharField(max_length=150, verbose_name='Nombre Procedimiento'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 19, 33, 20, 957913), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
