# Generated by Django 5.0.7 on 2025-03-12 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0024_alter_cirugia_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumocirugia',
            name='obligatoria',
            field=models.BooleanField(default=False, verbose_name='Obligatoria'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='C:\\proyectou58\\photos\\VU58Foto.png', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 22, 50, 0, 922775), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
