# Generated by Django 5.0.7 on 2025-03-13 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0026_montoincremento_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 23, 4, 33, 699315), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
