# Generated by Django 5.0.7 on 2025-03-15 01:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0028_alter_consumocirugia_cirugia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='atencion_inmediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediata', verbose_name='atencion_inmediata'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='atencion_inmediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediata', verbose_name='atencion_inmediata'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 21, 43, 20, 260552), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido'), ('F', 'Fallecido'), ('X', 'Temporal')], default='A', max_length=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='cantidad_uso',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Cantidad Uso'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='Cirugia'),
        ),
    ]
