# Generated by Django 5.0.7 on 2025-03-17 02:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0031_alter_inventariosolicitud_fecha_despacho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencioninmediata',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.habitacion', verbose_name='Habitacion numero'),
        ),
        migrations.AddField(
            model_name='atencioninmediata',
            name='hora_procedimiento',
            field=models.TimeField(null=True, verbose_name='hora ingreso'),
        ),
        migrations.AddField(
            model_name='cuentaxcobrar',
            name='atencion_inmediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediata', verbose_name='atencion_inmediata'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 1, 41, 370349), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='C:/proyectoU58/photos/VU58Foto.png', null=True, upload_to='photos/'),
        ),
    ]
