# Generated by Django 5.0.7 on 2025-03-18 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0032_atencioninmediata_habitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 21, 36, 1, 95005), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
