# Generated by Django 5.0.7 on 2025-03-19 04:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0033_alter_inventariosolicitud_fecha_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='altamedica',
            name='atencion_inmediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediata', verbose_name='atencion_inmediata'),
        ),
        migrations.AddField(
            model_name='inventariodescarga',
            name='atencion_inmediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediata', verbose_name='atencion_inmediata'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 0, 2, 45, 422025), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
