# Generated by Django 5.0.7 on 2025-03-20 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0034_altamedica_atencion_inmediata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 23, 38, 28, 121764), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
