# Generated by Django 5.0.7 on 2025-03-28 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0039_alter_detallenotaentrega_costo_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='uci',
            field=models.BooleanField(default=False, verbose_name='estubo uci'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 23, 19, 21, 382389), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
