# Generated by Django 5.0.7 on 2025-03-30 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0040_cirugia_uci_alter_inventariosolicitud_fecha_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefacturaproveedor',
            name='precio_bs',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Precio Bs'),
        ),
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='costo_bs',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Costo Bs'),
        ),
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 10, 58, 0, 104942), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
