# Generated by Django 5.0.7 on 2025-03-30 15:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0041_alter_detallefacturaproveedor_precio_bs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 11, 3, 15, 765527), null=True, verbose_name='Fecha Actualizacion'),
        ),
        migrations.CreateModel(
            name='TrasladoUci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Alta')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('condiciones_egreso', models.TextField(blank=True, default='Condiciones de Egreso', max_length=1000, null=True, verbose_name='Condicion Egreso')),
                ('diagnostico_egreso', models.TextField(blank=True, default='Diagnostico de Egreso', max_length=1000, null=True, verbose_name='Diagnostico Egreso')),
                ('diagnostico_ingreso', models.TextField(blank=True, default='Diagnostico de Ingreso', max_length=1000, null=True, verbose_name='Diagnostico Ingreso')),
                ('tratamiento_recibido', models.TextField(blank=True, default='Tratamiento Recibido', max_length=1000, null=True, verbose_name='Tratamiento recibido')),
                ('cirugia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='Cirugia')),
                ('medico_egreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.medico', verbose_name='Medico de Egreso')),
            ],
            options={
                'verbose_name': 'AltaMedica',
                'verbose_name_plural': 'Altas Medicas',
            },
        ),
    ]
