# Generated by Django 5.0.7 on 2025-04-02 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0042_alter_inventariosolicitud_fecha_despacho_trasladouci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosolicitud',
            name='fecha_despacho',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 0, 2, 36, 905353), null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
