# Generated by Django 5.0.7 on 2025-04-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0045_alter_inventario_unidad_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefacturaproveedor',
            name='precio_bs',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Precio Bs'),
        ),
    ]
