# Generated by Django 5.0.7 on 2025-05-07 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0049_detalleconsumocirugia_usuario_cirugia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprefactura',
            name='detallepresupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallepresupuesto', verbose_name='Detalle de Presupuesto'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Factor Incremento'),
        ),
        migrations.CreateModel(
            name='LogDetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=200, null=True, verbose_name='DetalleBaremo')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('nota', models.CharField(blank=True, max_length=200, null=True, verbose_name='nota')),
                ('factor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='factor')),
                ('monto_original', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto_original')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.presupuesto', verbose_name='presupuesto ID')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'LogDetallePresupuesto',
                'verbose_name_plural': 'LogDetallePresupuestos',
            },
        ),
    ]
