# Generated by Django 5.0.7 on 2025-05-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0052_debitocredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitocredito',
            name='fechatransaccion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
