# Generated by Django 5.0.7 on 2025-07-14 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0060_logeliminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumocirugia',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.cirugia', verbose_name='Cirugia'),
        ),
        migrations.AlterField(
            model_name='inventariodescarga',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.cirugia', verbose_name='Cirugia ID'),
        ),
    ]
