# Generated by Django 5.0.7 on 2025-07-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0061_alter_consumocirugia_cirugia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugia',
            name='precarga',
            field=models.PositiveIntegerField(default=True, verbose_name='Precarga de medicina'),
        ),
    ]
