# Generated by Django 5.0.7 on 2025-07-21 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0062_alter_cirugia_precarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeracionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.PositiveIntegerField(verbose_name='Numero Factura')),
                ('numero_control', models.PositiveIntegerField(verbose_name='Numero control')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
            ],
            options={
                'verbose_name': 'NumeracionFactura',
                'verbose_name_plural': 'NumeracionesFacturas',
            },
        ),
        migrations.AddField(
            model_name='debitocredito',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='motivo'),
        ),
        migrations.AddField(
            model_name='detalleprefactura',
            name='grupo_factura',
            field=models.PositiveIntegerField(default=0, verbose_name='grupo_factura'),
        ),
        migrations.AlterField(
            model_name='cuentaxcobrar',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cirugia', to='appcc58.cirugia', verbose_name='Cirugia'),
        ),
        migrations.AlterField(
            model_name='cuentaxcobrar',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='appcc58.presupuesto', verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='detallepresupuesto',
            name='presupuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detallepresupuesto_set', to='appcc58.presupuesto', verbose_name='Presupuesto'),
        ),
    ]
