# Generated by Django 5.0.7 on 2025-08-11 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0068_nombresubbaremo_baremo_fecha_act_baremo_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='altamedica',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_creacion'),
        ),
        migrations.AddField(
            model_name='notacreditoctacobrar',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_pago'),
        ),
        migrations.AlterField(
            model_name='cuentaxcobrar',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.referencia', verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.religion', verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.responsable', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
