# Generated by Django 5.0.7 on 2025-08-22 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0071_bancolocal_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecuentacobrar',
            name='notacredito_manual_id',
            field=models.PositiveIntegerField(default=0, verbose_name='id notacredito_manual_id'),
        ),
        migrations.AddField(
            model_name='notacreditoctacobrar',
            name='autogenerada',
            field=models.BooleanField(default=False, verbose_name='Nota de credito autogenerada'),
        ),
        migrations.AddField(
            model_name='pagador',
            name='notacredito_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notacredito_origen', to='appcc58.notacreditoctacobrar', verbose_name='notacredito_origen'),
        ),
    ]
