# Generated by Django 5.0.7 on 2025-09-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0076_baremovinculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='baremo',
            name='inactivar',
            field=models.BooleanField(default=False, verbose_name='Inactivar'),
        ),
    ]
