# Generated by Django 5.0.7 on 2025-09-04 00:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0077_baremo_inactivar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='numeracionfactura',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.cirugia', verbose_name='Cirugia ID'),
        ),
        migrations.AddField(
            model_name='numeracionfactura',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha_creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeracionfactura',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True, verbose_name='fecha_factura'),
        ),
        migrations.AddField(
            model_name='numeracionfactura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='numeracionfactura',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Fecha Actualizacion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetallePrefactura',
        ),
    ]
