# Generated by Django 5.0.7 on 2025-09-08 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0079_detalleprefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumocirugia',
            name='baremo_cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.detallebaremo', verbose_name='baremo_cobro'),
        ),
        migrations.AddField(
            model_name='consumocirugia',
            name='seleccionado',
            field=models.BooleanField(default=False, verbose_name='seleccionado'),
        ),
    ]
