# Generated by Django 5.0.7 on 2025-10-10 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0080_consumocirugia_baremo_cobro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodescarga',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InventarioDescarga', to='appcc58.inventario', verbose_name='Inventario'),
        ),
    ]
