# Generated by Django 5.0.7 on 2025-10-17 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0081_alter_inventariodescarga_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='deposito_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.deposito', verbose_name='deposito_carga_id'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.inventario', verbose_name='inventario_id'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='abono_id',
            field=models.PositiveBigIntegerField(default=0, verbose_name='id_abono_correspondiente'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='estatus',
            field=models.CharField(blank=True, default='PEN', max_length=3, null=True, verbose_name='estatus'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='sustraendo_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='sustraendo_bs'),
        ),
        migrations.AlterField(
            model_name='abonocuentapagar',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_afectada', to='appcc58.facturaproveedor', verbose_name='factura pagar'),
        ),
    ]
