# Generated by Django 5.0.7 on 2025-10-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0086_alter_consumocirugia_fecha_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumocirugia',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
