# Generated by Django 5.0.7 on 2025-11-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0087_alter_consumocirugia_fecha_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebaremo',
            name='activar_retencion',
            field=models.BooleanField(default=True, verbose_name='activar_retencion'),
        ),
        migrations.AddField(
            model_name='detallecuentacobrar',
            name='estatus',
            field=models.CharField(blank=True, default=' * ', max_length=50, null=True, verbose_name='status'),
        ),
    ]
