# Generated by Django 5.0.7 on 2025-11-06 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0088_detallebaremo_activar_retencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='bancolocal',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='detalleprefactura',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='cirugia'),
        ),
        migrations.AddField(
            model_name='medico',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='medico',
            name='grupo',
            field=models.CharField(choices=[('M', 'Medico'), ('E', 'Enfermeria'), ('G', 'Grupo Medico'), ('S', 'Seguros')], default='M', max_length=1, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='pagomedico',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='atencioninmediata',
            name='fecha_act',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Actualizado el'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, verbose_name='Cedula / Rif'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='participaalta',
            field=models.BooleanField(default=False, verbose_name='Participa en alta medica'),
        ),
    ]
