# Generated by Django 5.0.7 on 2025-11-17 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0090_tratamiento_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='montoiva_dl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA MONTO DL'),
        ),
        migrations.AddField(
            model_name='facturamedico',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.facturaproveedor', verbose_name='factura'),
        ),
        migrations.AddField(
            model_name='facturamedico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.retencionislr', verbose_name='RetencionISLR'),
        ),
        migrations.AddField(
            model_name='medico',
            name='porcentaje_retencion_iva',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=10, verbose_name='% Retencion IVA'),
        ),
        migrations.AddField(
            model_name='retencionislr',
            name='baseimponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='baseimponible'),
        ),
        migrations.AddField(
            model_name='retencionislr',
            name='montofactura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='montofactura'),
        ),
        migrations.AddField(
            model_name='retencionislr',
            name='montoretencion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='montoretencion'),
        ),
        migrations.AddField(
            model_name='retencionislr',
            name='porcentaje_retencion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='porcentaje_retencion'),
        ),
        migrations.AddField(
            model_name='retencionislr',
            name='tipo_comprobante',
            field=models.CharField(default='FM', max_length=2, verbose_name='tipo_comprobante'),
        ),
        migrations.AlterField(
            model_name='detallefacturaproveedor',
            name='montoiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA MONTO'),
        ),
        migrations.CreateModel(
            name='PagoReciboFacturaMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('factura_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_legal', to='appcc58.facturaproveedor', verbose_name='Factura')),
                ('factura_recibo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_recibo', to='appcc58.facturaproveedor', verbose_name='Factura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'PagoReciboFacturaMedico',
                'verbose_name_plural': 'PagosRecibosFacturasMedicos',
            },
        ),
    ]
