# Generated by Django 5.0.7 on 2025-12-01 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0093_atencioninmediatacortesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='altamedica',
            name='atencion_cortesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia'),
        ),
        migrations.AddField(
            model_name='consumocirugia',
            name='atencion_cortesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia'),
        ),
        migrations.AddField(
            model_name='cuentaxcobrar',
            name='atencion_cortesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia'),
        ),
        migrations.AddField(
            model_name='inventariodescarga',
            name='atencion_cortesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia'),
        ),
        migrations.AddField(
            model_name='notaquirurgica',
            name='atencion_cortesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='atencion_cortesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='atencion_cortesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='grupo',
            field=models.CharField(choices=[('M', 'Medico y Enfermeria'), ('E', 'Empleados y Contratos'), ('G', 'Grupo Medico '), ('S', 'Seguros y Gobierno')], default='M', max_length=1, verbose_name='Grupo'),
        ),
    ]
