# Generated by Django 5.0.7 on 2026-01-14 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0094_altamedica_atencion_cortesia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecuentacobrar',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='monto_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto_descuento'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='porcentaje_descuento'),
        ),
        migrations.AddField(
            model_name='medico',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='C:/proyectoU58/photos/MedicoU58.png', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='logcuentacobrar',
            name='nota',
            field=models.CharField(blank=True, default='Eliminacion de Pago en cuenta x cobrar', max_length=500, null=True, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='logdetallepresupuesto',
            name='nota',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='loginventario',
            name='nota',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nota'),
        ),
        migrations.CreateModel(
            name='ConsultaPreanestesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('fecha_consulta', models.DateField(blank=True, null=True, verbose_name='fecha_consulta')),
                ('antecedente_medico', models.TextField(blank=True, null=True, verbose_name='antecedente_medico')),
                ('antecedente_qx', models.TextField(blank=True, null=True, verbose_name='antecedente_qx')),
                ('alergia', models.TextField(blank=True, null=True, verbose_name='alergia')),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='peso')),
                ('talla', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='talla')),
                ('imc', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='imc')),
                ('ta', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ta')),
                ('fr', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='fr')),
                ('fc', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='fc')),
                ('malla_i', models.BooleanField(default=False, verbose_name='malla_i')),
                ('malla_ii', models.BooleanField(default=False, verbose_name='malla_ii')),
                ('malla_iii', models.BooleanField(default=False, verbose_name='malla_iii')),
                ('malla_iv', models.BooleanField(default=False, verbose_name='malla_iv')),
                ('dtm', models.CharField(blank=True, max_length=40, null=True, verbose_name='dtm')),
                ('dem', models.CharField(blank=True, max_length=40, null=True, verbose_name='dem')),
                ('ao', models.CharField(blank=True, max_length=40, null=True, verbose_name='ao')),
                ('rhmi', models.CharField(blank=True, max_length=40, null=True, verbose_name='rhmi')),
                ('aao', models.CharField(blank=True, max_length=40, null=True, verbose_name='aao')),
                ('nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='nota')),
                ('hb', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='hb')),
                ('hto', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='hto')),
                ('plaq', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='plaq')),
                ('pt', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='pt')),
                ('ptt', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ptt')),
                ('glisemia', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='glisemia')),
                ('urea', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='urea')),
                ('creatinina', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='creatinina')),
                ('hiv', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='hiv')),
                ('vdrl', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='vdrl')),
                ('ekg', models.CharField(blank=True, max_length=100, null=True, verbose_name='ekg')),
                ('rxtorax', models.CharField(blank=True, max_length=100, null=True, verbose_name='rxtorax')),
                ('ecomls', models.CharField(blank=True, max_length=100, null=True, verbose_name='ecomls')),
                ('eva_preoperatoria', models.TextField(blank=True, null=True, verbose_name='eva_preoperatoria')),
                ('evaluaciones', models.TextField(blank=True, null=True, verbose_name='evaluaciones')),
                ('categoria_asa_i', models.BooleanField(default=False, verbose_name='categoria_asa_i')),
                ('categoria_asa_ii', models.BooleanField(default=False, verbose_name='categoria_asa_ii')),
                ('categoria_asa_iii', models.BooleanField(default=False, verbose_name='categoria_asa_iii')),
                ('categoria_asa_iv', models.BooleanField(default=False, verbose_name='categoria_asa_iv')),
                ('categoria_asa_v', models.BooleanField(default=False, verbose_name='categoria_asa_v')),
                ('categoria_asa_e', models.BooleanField(default=False, verbose_name='categoria_asa_e')),
                ('recomendacion', models.TextField(blank=True, null=True, verbose_name='recomendacion')),
                ('ipa', models.TextField(blank=True, default=0, null=True, verbose_name='ipa')),
                ('cirugia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='cirugia')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.medico', verbose_name='medico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'ConsultaPreanestesia',
                'verbose_name_plural': 'ConsultasPreanestesias',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPreanestesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=250, unique=True, verbose_name='pregunta')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('modulo', models.CharField(default='EVPA', max_length=4, verbose_name='modulo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'EvaluacionPreanestesia',
                'verbose_name_plural': 'EvaluacionesPreanestesias ',
            },
        ),
        migrations.CreateModel(
            name='LogDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='monto_descuento')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='porcentaje_descuento')),
                ('monto_aplicar_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='monto_aplicar_descuento')),
                ('nuevo_monto', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='nuevo_monto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('cirugia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='cirugia')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.presupuesto', verbose_name='presupuesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'LogDescuento',
                'verbose_name_plural': 'LogDescuentos ',
            },
        ),
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField()),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='detalle')),
                ('cantidad', models.IntegerField(default=0, verbose_name='cantidad')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcc58.consultapreanestesia', verbose_name='consulta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcc58.evaluacionpreanestesia', verbose_name='pregunta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'RespuestaEvaluacion',
                'verbose_name_plural': 'RespuestaEvaluaciones ',
            },
        ),
    ]
