# Generated by Django 5.0.7 on 2026-01-15 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0095_detallecuentacobrar_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('fecha_consulta', models.DateField(blank=True, null=True, verbose_name='fecha_consulta')),
                ('contacto', models.CharField(blank=True, max_length=200, null=True, verbose_name='contacto')),
                ('telefono', models.CharField(blank=True, max_length=11, verbose_name='Telefono principal')),
                ('req_imi', models.BooleanField(default=False, verbose_name='req_imi')),
                ('req_oi', models.BooleanField(default=False, verbose_name='req_oi')),
                ('req_cc', models.BooleanField(default=False, verbose_name='req_cc')),
                ('req_tap', models.BooleanField(default=False, verbose_name='req_tap')),
                ('req_ep', models.BooleanField(default=False, verbose_name='req_ep')),
                ('req_ec', models.BooleanField(default=False, verbose_name='req_ec')),
                ('req_epre', models.BooleanField(default=False, verbose_name='req_epre')),
                ('usu_epreoperatorio', models.BooleanField(default=False, verbose_name='usu_epreoperatorio')),
                ('usu_ecardiovascular', models.BooleanField(default=False, verbose_name='usu_ecardiovascular')),
                ('usu_preanestesica', models.BooleanField(default=False, verbose_name='usu_preanestesica')),
                ('motivo_consulta', models.CharField(max_length=200, verbose_name='motivo_consulta')),
                ('enfermedad_actual', models.TextField(blank=True, null=True, verbose_name='enfermedad_actual')),
                ('idx', models.CharField(blank=True, max_length=200, null=True, verbose_name='idx')),
                ('servicio_cargo', models.CharField(blank=True, max_length=200, null=True, verbose_name='servicio_cargo')),
                ('antecedentes_familiar', models.TextField(blank=True, null=True, verbose_name='antecedentes_familiar')),
                ('habito', models.TextField(blank=True, null=True, verbose_name='habito')),
                ('antecedente_qx', models.TextField(blank=True, null=True, verbose_name='antecedente_qx')),
                ('estudios', models.TextField(blank=True, null=True, verbose_name='estudios')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='diagnostico')),
                ('plan', models.TextField(blank=True, null=True, verbose_name='plan')),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='peso')),
                ('talla', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='talla')),
                ('imc', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='imc')),
                ('pa', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='pa')),
                ('fr', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='fr')),
                ('fc', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='fc')),
                ('temp', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='temp')),
                ('cirugia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='cirugia')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.medico', verbose_name='medico')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.responsable', verbose_name='responsable')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'HistoriaClinica',
                'verbose_name_plural': 'HistoriasClinicas',
            },
        ),
        migrations.CreateModel(
            name='EvolucionHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=1000, null=True, verbose_name='detalle')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('fecha_consulta', models.DateTimeField(blank=True, null=True, verbose_name='fecha_consulta')),
                ('tipo', models.CharField(blank=True, choices=[('em', 'Evolucion medica'), ('ee', 'Evolucion enfermeria'), ('om', 'Ordenes medicas')], max_length=2, null=True, verbose_name='tipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('historiaclinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.historiaclinica', verbose_name='historiaclinica')),
            ],
            options={
                'verbose_name': 'EvolucionHistoria',
                'verbose_name_plural': 'EvolucionesHistorias',
            },
        ),
    ]
