# Generated by Django 5.0.7 on 2026-01-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0096_historiaclinica_evolucionhistoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultapreanestesia',
            name='nota',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True, default='Escriba su direccion', max_length=500, null=True, verbose_name='Direccion / Zona'),
        ),
    ]
