# Generated by Django 5.0.7 on 2026-01-23 02:33

import appcc58.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0097_alter_consultapreanestesia_nota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepresupuesto',
            name='monto_descuento_pr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto_descuento_pr'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='porcentaje_descuento_pr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='porcentaje_descuento_pr'),
        ),
        migrations.AlterField(
            model_name='detallecirugia',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidad', verbose_name='Unidad Baremo'),
        ),
        migrations.CreateModel(
            name='DocumentoCirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=appcc58.models.ruta_cirugia, verbose_name='archivo')),
                ('cargado', models.ImageField(upload_to='cirugia/', verbose_name='cargado')),
                ('tipo', models.CharField(default='laboratorio', max_length=50, verbose_name='tipo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='fecha_subida')),
                ('cirugia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcc58.cirugia', verbose_name='cirugia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'DocumentoCirugia',
                'verbose_name_plural': 'DocumentosCirugias',
            },
        ),
        migrations.CreateModel(
            name='RegistroPresupuestoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='appcc58.presupuesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
