# Generated by Django 5.0.7 on 2026-02-03 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0099_alter_facturaproveedor_numerocontrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonocuentapagar',
            name='factura_pago_multiple',
            field=models.BooleanField(default=False, verbose_name='pago multiple facturas'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='multiple_factura',
            field=models.BooleanField(default=False, verbose_name='Pago de multiples facturas'),
        ),
        migrations.AlterField(
            model_name='abonocuentapagar',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion pago'),
        ),
        migrations.AlterField(
            model_name='abonocuentapagar',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.transaccion', verbose_name='Transaccion_ID'),
        ),
        migrations.CreateModel(
            name='TransaccionFacturaMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto aplicado Bs')),
                ('monto_aplicado_dolar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto aplicado USD')),
                ('abono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abono', to='appcc58.abonocuentapagar')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcc58.facturaproveedor')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='appcc58.transaccion')),
            ],
            options={
                'verbose_name': 'Factura aplicada a transacción',
                'verbose_name_plural': 'Facturas aplicadas a transacción',
            },
        ),
    ]
