# Generated by Django 5.0.7 on 2026-03-13 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0103_reutilizacioninventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='moneda_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.moneda', verbose_name='moneda_pago'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='porcentaje_retencion_gasto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='porcentaje_retencion_gasto'),
        ),
        migrations.AddField(
            model_name='lugarconsumo',
            name='posicion',
            field=models.PositiveIntegerField(default=0, verbose_name='posicion'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
