# Generated by Django 5.0.7 on 2026-03-16 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0104_detallefacturaproveedor_moneda_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenotaentrega',
            name='cantidad_a_factura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_a_factura'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='convertido_a_factura',
            field=models.BooleanField(default=False, verbose_name='convertido_a_factura'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='factura',
            field=models.BooleanField(default=True, verbose_name='factura'),
        ),
        migrations.AddField(
            model_name='notaentregacompra',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.retencion', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='notaentregacompra',
            name='porcentaje_retencion_islr',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='porcentaje_retencion_islr'),
        ),
    ]
