# Generated by Django 5.0.7 on 2026-03-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0105_detallenotaentrega_cantidad_a_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaentregacompra',
            name='convertida_factura_total',
            field=models.BooleanField(default=False, verbose_name='convertida_factura_total'),
        ),
        migrations.AlterField(
            model_name='notaentregacompra',
            name='porcentaje_retencion_islr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='porcentaje_retencion_islr'),
        ),
    ]
