# Generated by Django 5.0.7 on 2026-03-27 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0108_consultapreanestesia_firma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturamedico',
            name='baseimponible',
        ),
        migrations.RemoveField(
            model_name='facturamedico',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='facturamedico',
            name='montoretenido',
        ),
        migrations.RemoveField(
            model_name='facturamedico',
            name='netopagado',
        ),
        migrations.RemoveField(
            model_name='facturamedico',
            name='pretencion',
        ),
        migrations.AddField(
            model_name='distribucionpagomedico',
            name='monto_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='monto bs'),
        ),
        migrations.AddField(
            model_name='distribucionpagomedico',
            name='tx',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='tx'),
        ),
        migrations.AlterField(
            model_name='facturamedico',
            name='comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.retencionislr', verbose_name='comprobante'),
        ),
        migrations.AlterField(
            model_name='facturamedico',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Entrega'),
        ),
    ]
