# Generated by Django 5.0.7 on 2026-04-06 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0111_consultapreanestesia_leucosito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddIndex(
            model_name='inventariodescarga',
            index=models.Index(fields=['inventario', 'deposito'], name='appcc58_inv_inventa_7f883d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventariodescarga',
            index=models.Index(fields=['tipodescarga'], name='appcc58_inv_tipodes_fb80ae_idx'),
        ),
    ]
