# Generated by Django 5.0.14 on 2026-04-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0112_especialidad_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'UnidadProducto',
                'verbose_name_plural': 'Unidades Productos',
            },
        ),
        migrations.AlterModelOptions(
            name='unidadcompra',
            options={'verbose_name': 'UnidadCompra', 'verbose_name_plural': 'Unidad Compra de Inventarios'},
        ),
        migrations.AddField(
            model_name='inventariohistoria',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='factor'),
        ),
        migrations.AddField(
            model_name='inventariohistoria',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appcc58.laboratoriomedicina', verbose_name='laboratorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentacionmedicina',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='presentacionmedicina',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='cantidad'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='cantidad_bulto',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='cantidad_bulto'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='cantidad_unidad_bulto',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='cantidad_unidad_bulto'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='clasificacion'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='presentacionmedicina',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='unidad'),
        ),
    ]
