# Generated by Django 5.0.14 on 2026-04-06 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0113_unidadproducto_alter_unidadcompra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariohistoria',
            name='factura_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_entrega', to='appcc58.facturaproveedor', verbose_name='factura_compra'),
        ),
    ]
