# Generated by Django 5.0.7 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0113_unidadproducto_alter_unidadcompra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='C:/U58-QA/photos/MedicoU58.png', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='C:/U58-AQ/photos/VU58Foto.png', null=True, upload_to='photos/'),
        ),
    ]
