# Generated by Django 5.0.14 on 2026-04-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0114_inventariohistoria_factura_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.categoriainventario', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_presentacion_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nueva_presentacion_salida', to='appcc58.presentacionmedicina', verbose_name='Presentacion Salida'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_unidadcompra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nueva_unidadcompra', to='appcc58.unidadcompra', verbose_name='unidadcompra'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nuevo_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.laboratoriomedicina', verbose_name='Laboratorio'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nuevo_lote',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lote Producto'),
        ),
    ]
