# Generated by Django 5.0.14 on 2026-04-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0115_detallefacturaproveedor_nueva_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_fechaelaboracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha elaboracion'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_fechavencimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nuevo_nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nuevo_nombre_comercial'),
        ),
    ]
