# Generated by Django 5.0.7 on 2026-05-06 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0115_remove_facturaproveedor_centro_costo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nc',
            field=models.BooleanField(default=False, verbose_name='nc inventario'),
        ),
        migrations.CreateModel(
            name='CentroCostoFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='descripcion')),
                ('cuenta_asociada', models.CharField(blank=True, max_length=50, null=True, verbose_name='cuenta_asociada')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'CentroCostoFacturaCompra',
                'verbose_name_plural': 'CentroCostoFacturaCompras',
            },
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.centrocostofacturacompra', verbose_name='centro_costo'),
        ),
    ]
