# Generated by Django 5.0.14 on 2026-04-13 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0115_remove_facturaproveedor_centro_costo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'UnidadProducto',
                'verbose_name_plural': 'Unidades Productos',
            },
        ),
        migrations.AlterModelOptions(
            name='unidadcompra',
            options={'verbose_name': 'UnidadCompra', 'verbose_name_plural': 'Unidad Compra de Inventarios'},
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.categoriainventario', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_fechaelaboracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha elaboracion'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_fechavencimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_presentacion_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nueva_presentacion_salida', to='appcc58.presentacionmedicina', verbose_name='Presentacion Salida'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_unidadcompra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nueva_unidadcompra', to='appcc58.unidadcompra', verbose_name='unidadcompra'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nuevo_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.laboratoriomedicina', verbose_name='Laboratorio'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nuevo_lote',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lote Producto'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nuevo_nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nuevo_nombre_comercial'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='precio_unico_factor_dl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='precio_unico_factor_dl'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='unidades_con_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='unidades_con_factor'),
        ),
        migrations.AddField(
            model_name='inventariohistoria',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='factor'),
        ),
        migrations.AddField(
            model_name='inventariohistoria',
            name='factura_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_entrega', to='appcc58.facturaproveedor', verbose_name='factura_compra'),
        ),
        migrations.AddField(
            model_name='inventariohistoria',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.laboratoriomedicina', verbose_name='laboratorio'),
        ),
        migrations.AddField(
            model_name='inventariohistoria',
            name='piva',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='piva'),
        ),
        migrations.AddField(
            model_name='presentacionmedicina',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='presentacionmedicina',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='cantidad'),
        ),
        migrations.AddField(
            model_name='reutilizacioninventario',
            name='deposito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appcc58.deposito', verbose_name='deposito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reutilizacioninventario',
            name='noreutilizable',
            field=models.BooleanField(default=False, verbose_name='noreuntilizable'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='cantidad_bulto',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='cantidad_bulto'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='cantidad_unidad_bulto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='cantidad_unidad_bulto'),
        ),
        migrations.CreateModel(
            name='CentroCostoFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='descripcion')),
                ('cuenta_asociada', models.CharField(blank=True, max_length=50, null=True, verbose_name='cuenta_asociada')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'CentroCostoFacturaCompra',
                'verbose_name_plural': 'CentroCostoFacturaCompras',
            },
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.centrocostofacturacompra', verbose_name='centro_costo'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='nueva_clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='clasificacion'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='presentacionmedicina',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.unidadproducto', verbose_name='unidad'),
        ),
    ]
