# Generated by Django 5.0.14 on 2026-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0116_detallefacturaproveedor_nueva_fechaelaboracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='precio_unico_factor_dl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='precio_unico_factor_dl'),
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='unidades_con_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='unidades_con_factor'),
        ),
    ]
