# Generated by Django 5.0.7 on 2026-05-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0116_detallefacturaproveedor_nc_centrocostofacturacompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaquirurgica',
            name='caso_cerrado',
            field=models.BooleanField(default=False, verbose_name='caso_cerrado'),
        ),
    ]
