# Generated by Django 5.0.14 on 2026-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0116_unidadproducto_alter_unidadcompra_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremoPagoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='precio')),
            ],
            options={
                'verbose_name': 'BaremoPagoTercero',
                'verbose_name_plural': 'BaremoPagoTerceros',
            },
        ),
    ]
