# Generated by Django 5.0.14 on 2026-04-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0117_detallefacturaproveedor_precio_unico_factor_dl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariohistoria',
            name='piva',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='piva'),
        ),
    ]
