# Generated by Django 5.0.7 on 2026-05-16 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0117_notaquirurgica_caso_cerrado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremoPagoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='precio')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'BaremoPagoTercero',
                'verbose_name_plural': 'BaremoPagoTerceros',
            },
        ),
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='baremo_pago_tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.baremopagotercero', verbose_name='baremo_pago_tercero'),
        ),
    ]
