# Generated by Django 5.0.7 on 2026-05-17 13:58

import appcc58.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0118_baremopagotercero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Módulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionEspecificaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Opción Específica')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_especificas', to='appcc58.modulosistema', verbose_name='Módulo Principal')),
            ],
            options={
                'verbose_name': 'Opción Específica',
                'verbose_name_plural': 'Opciones Específicas',
                'ordering': ['nombre'],
                'unique_together': {('modulo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del problema')),
                ('tipo_solicitud', models.CharField(choices=[('bug', 'Reportar un Error (Bug)'), ('mejora', 'Sugerir una Mejora'), ('soporte', 'Duda de Usuario / Soporte Técnico')], max_length=20, verbose_name='Tipo de solicitud')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to=appcc58.models.ruta_adjuntos_soporte, verbose_name='Archivo Adjunto')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_progreso', 'En Progreso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20, verbose_name='Estado del Ticket')),
                ('prioridad_interna', models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=15, null=True, verbose_name='Prioridad Interna')),
                ('comentarios_tecnicos', models.TextField(blank=True, null=True, verbose_name='Notas del Equipo de Soporte')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('fecha_estimada_culminacion', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de culminación')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcc58.modulosistema', verbose_name='Módulo del sistema')),
                ('opcion_especifica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcc58.opcionespecificamodulo', verbose_name='Opción específica del módulo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Soporte',
                'verbose_name_plural': 'Solicitudes de Soporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
