# Generated by Django 5.0.14 on 2026-04-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0118_inventariohistoria_piva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariohistoria',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.laboratoriomedicina', verbose_name='laboratorio'),
        ),
    ]
