# Generated by Django 5.0.14 on 2026-04-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0120_remove_baremopagotercero_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baremopagotercero',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
