# Generated by Django 5.0.14 on 2026-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0120_centrocostofacturacompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocostofacturacompra',
            name='cuenta_asociada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cuenta_asociada'),
        ),
        migrations.AlterField(
            model_name='centrocostofacturacompra',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='centrocostofacturacompra',
            name='nombre',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nombre'),
        ),
    ]
