# Generated by Django 5.0.7 on 2026-05-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0120_alter_solicitudsoporte_tipo_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaquirurgica',
            name='excepcion_pago',
            field=models.BooleanField(default=False, verbose_name='excepcion_pago'),
        ),
    ]
