# Generated by Django 5.0.14 on 2026-04-22 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0121_alter_baremopagotercero_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baremopagotercero',
            name='actualizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='baremopagotercero',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='precio'),
        ),
    ]
