# Generated by Django 5.0.14 on 2026-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0121_alter_centrocostofacturacompra_cuenta_asociada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocostofacturacompra',
            name='nombre',
            field=models.CharField(default=1, max_length=25, unique=True, verbose_name='nombre'),
            preserve_default=False,
        ),
    ]
