# Generated by Django 5.0.7 on 2026-05-20 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0121_notaquirurgica_excepcion_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditoctacobrar',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.formapago', verbose_name='forma_pago'),
        ),
        migrations.CreateModel(
            name='HistoriaNotaCreditoCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('monto_aplicado_dl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo')),
                ('monto_aplicado_bs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='saldo_bs')),
                ('tasa', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='tasa')),
                ('fechatasa', models.DateField(blank=True, null=True, verbose_name='Fecha tasa bcv')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion pago')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='fecha_pago')),
                ('cuentaxcobrar_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.cuentaxcobrar', verbose_name='CuentaCobrar')),
                ('detallecuentaxcobrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallecuentacobrar', verbose_name='DetalleCuentaCobrar')),
                ('notacredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='appcc58.notacreditoctacobrar', verbose_name='nota credito padre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'HistoriaNotaCreditoCC',
                'verbose_name_plural': 'HistoriasNotasCreditoCCs',
            },
        ),
    ]
