# Generated by Django 5.0.14 on 2026-04-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0122_baremopagotercero_actualizado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baremopagotercero',
            old_name='actualizado',
            new_name='usuario',
        ),
    ]
