# Generated by Django 5.0.7 on 2026-06-12 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0127_consultapreanestesia_spo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositouso',
            options={},
        ),
        migrations.AddField(
            model_name='deposito',
            name='siglas',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Siglas'),
        ),
        migrations.AddIndex(
            model_name='depositouso',
            index=models.Index(fields=['inventario'], name='appcc58_dep_inventa_4e9344_idx'),
        ),
        migrations.AddIndex(
            model_name='depositouso',
            index=models.Index(fields=['deposito'], name='appcc58_dep_deposit_824577_idx'),
        ),
        migrations.AddIndex(
            model_name='depositouso',
            index=models.Index(fields=['inventario', 'deposito'], name='appcc58_dep_inventa_09f401_idx'),
        ),
    ]
