# Generated by Django 5.0.7 on 2026-06-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0128_alter_depositouso_options_deposito_siglas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='prefactura_consolidada',
            field=models.BooleanField(default=False, verbose_name='prefactura_consolidada'),
        ),
    ]
