# Generated by Django 5.0.14 on 2026-05-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0128_notacreditoctacobrar_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaquirurgica',
            name='caso_cerrado',
            field=models.BooleanField(default=False, verbose_name='caso_cerrado'),
        ),
    ]
