# Generated by Django 5.0.7 on 2026-06-13 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0129_facturaproveedor_prefactura_consolidada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoCtaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('monto_nota_credito', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='monto_nota_credito')),
                ('tasa', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='tasa')),
                ('fechatasa', models.DateField(blank=True, null=True, verbose_name='Fecha tasa bcv')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion pago')),
                ('aplicada', models.BooleanField(default=False, verbose_name='aplicada')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.facturaproveedor', verbose_name='factura')),
                ('forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.formapago', verbose_name='forma_pago')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.medico', verbose_name='medico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'NotaCreditoCtaPagar',
                'verbose_name_plural': 'NotaCreditoCtaPagars',
            },
        ),
        migrations.CreateModel(
            name='HistoriaNotaCreditoCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion')),
                ('monto_aplicado_dl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo')),
                ('monto_aplicado_bs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='saldo_bs')),
                ('tasa', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='tasa')),
                ('fechatasa', models.DateField(blank=True, null=True, verbose_name='Fecha tasa bcv')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion pago')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='fecha_pago')),
                ('detallefactura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallefacturaproveedor', verbose_name='detallefactura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('notacredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historialescxp', to='appcc58.notacreditoctapagar', verbose_name='nota credito padre')),
            ],
            options={
                'verbose_name': 'HistoriaNotaCreditoCP',
                'verbose_name_plural': 'HistoriaNotaCreditoCPs',
            },
        ),
    ]
