# Generated by Django 5.0.14 on 2026-05-16 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0129_notaquirurgica_caso_cerrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Módulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionEspecificaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Opción Específica')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_especificas', to='appcc58.modulosistema', verbose_name='Módulo Principal')),
            ],
            options={
                'verbose_name': 'Opción Específica',
                'verbose_name_plural': 'Opciones Específicas',
                'ordering': ['nombre'],
                'unique_together': {('modulo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del problema')),
                ('tipo_solicitud', models.CharField(choices=[('bug', 'Reportar un Error (Bug)'), ('mejora', 'Sugerir una Mejora'), ('soporte', 'Duda de Usuario / Soporte Técnico')], max_length=20, verbose_name='Tipo de solicitud')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='soporte/adjuntos/', verbose_name='Archivo Adjunto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcc58.modulosistema', verbose_name='Módulo del sistema')),
                ('opcion_especifica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcc58.opcionespecificamodulo', verbose_name='Opción específica del módulo')),
            ],
        ),
    ]
