# Generated by Django 5.0.7 on 2026-06-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0130_notacreditoctapagar_historianotacreditocp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='cierre_caso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cierre_caso'),
        ),
    ]
