# Generated by Django 5.0.7 on 2026-06-13 15:11

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0132_historicalinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMedico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=15, verbose_name='Cedula / Rif')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('rif', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rif')),
                ('nromsds', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nro MPPS')),
                ('nrocolegio', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nro Colegio')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('telefono1', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono principal')),
                ('telefono2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono secundario')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('porcentajepago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Pago')),
                ('por_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Descuento')),
                ('observacion', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('fecha_desde', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Ingreso')),
                ('participaalta', models.BooleanField(default=False, verbose_name='Participa en alta medica')),
                ('pagofrecuente', models.BooleanField(default=False, verbose_name='Pagador frecuente')),
                ('grupo', models.CharField(choices=[('M', 'Medico y Enfermeria'), ('E', 'Empleados y Contratos'), ('G', 'Grupo Medico '), ('S', 'Seguros y Gobierno')], default='M', max_length=1, verbose_name='Grupo')),
                ('fecha_act', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el')),
                ('porcentaje_retencion_iva', models.DecimalField(decimal_places=2, default=75, max_digits=10, verbose_name='% Retencion IVA')),
                ('fotoperfil', models.TextField(blank=True, default='C:/proyectoU58/photos/MedicoU58.png', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('especialidad', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.especialidad', verbose_name='especialidad')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipopersonal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.tipopersonal', verbose_name='Tipo Personal')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Aplicacion')),
            ],
            options={
                'verbose_name': 'historical Medico',
                'verbose_name_plural': 'historical Terceros Personal Medico',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
