# Generated by Django 5.0.14 on 2026-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0134_unidadproducto_alter_unidadcompra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultapreanestesia',
            name='vdrl',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='vdrl'),
        ),
    ]
