# Generated by Django 5.0.14 on 2026-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0135_alter_consultapreanestesia_vdrl'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='detalle_prefactura_origen_id',
            field=models.PositiveBigIntegerField(default=0, verbose_name='detalle_prefactura_origen'),
        ),
    ]
