# Generated by Django 5.0.14 on 2026-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0135_notaquirurgica_excepcion_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocostofacturacompra',
            name='servicio_padre',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='servicio_padre'),
        ),
    ]
