# Generated by Django 5.0.14 on 2026-05-20 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0136_centrocostofacturacompra_servicio_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecuentacobrar',
            name='forma_pago_nc_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.formapago', verbose_name='forma_pago_nc_padre'),
        ),
    ]
