# Generated by Django 5.0.14 on 2026-06-24 00:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0136_detallefacturaproveedor_detalle_prefactura_origen_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCuentaxCobrar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha Actualizacion')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atencion_cortesia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia')),
                ('atencion_inmediata', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.atencioninmediata', verbose_name='atencion_inmediata')),
                ('cirugia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.cirugia', verbose_name='Cirugia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.paciente', verbose_name='Paciente')),
                ('preingreso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.preingreso', verbose_name='preingreso')),
                ('presupuesto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.presupuesto', verbose_name='Presupuesto')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical CuentaxCobrar',
                'verbose_name_plural': 'historical Cuentas x Cobrar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDetalleCuentaCobrar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('montocobrar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto cobrar')),
                ('montocobrar_bs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='monto cobrar BS')),
                ('fecha_act', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha Actualizacion')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('estatus', models.CharField(blank=True, default=' * ', max_length=50, null=True, verbose_name='status')),
                ('nroretencion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nro Retencion')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Tasa BCV')),
                ('notacredito', models.BooleanField(default=False, verbose_name='Nota de credito aplicada')),
                ('notacredito_manual_id', models.PositiveIntegerField(default=0, verbose_name='id notacredito_manual_id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cuentacobrar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.cuentaxcobrar', verbose_name='CuentaxCobrar')),
                ('destino_pago', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.bancolocal', verbose_name='Destino Pago')),
                ('forma_pago_nc_padre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.formapago', verbose_name='forma_pago_nc_padre')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origen_pago', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.origenpago', verbose_name='Origen Pago')),
                ('retencion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.retencion', verbose_name='Retencion')),
                ('transaccion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.transaccion', verbose_name='Transaccion ID')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'historical DetalleCuentaCobrar',
                'verbose_name_plural': 'historical Detalle de CuentaCobrar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNotaCreditoCtaCobrar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_act', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha Actualizacion')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo')),
                ('saldo_bs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='saldo_bs')),
                ('tasa', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='tasa')),
                ('fechatasa', models.DateField(blank=True, null=True, verbose_name='Fecha tasa bcv')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion pago')),
                ('aplicada', models.BooleanField(default=False, verbose_name='aplicada')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='fecha_pago')),
                ('autogenerada', models.BooleanField(default=False, verbose_name='Nota de credito autogenerada')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cuentaxcobrar_aplicada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.cuentaxcobrar', verbose_name='CuentaCobrar')),
                ('detallecuentaxcobrar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.detallecuentacobrar', verbose_name='DetalleCuentaCobrar')),
                ('forma_pago', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.formapago', verbose_name='forma_pago')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pagador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.pagadorunico', verbose_name='pagador')),
                ('presupuesto_referencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.presupuesto', verbose_name='presupuesto_referencia')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical NotaCreditoCtaCobrar',
                'verbose_name_plural': 'historical NotasCreditosCtaCobrar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
