# Generated by Django 5.0.14 on 2026-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0137_detallecuentacobrar_forma_pago_nc_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempfecha',
            name='caso_cerrado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
