# Generated by Django 5.0.14 on 2026-06-24 01:48

import appcc58.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0137_historicalcuentaxcobrar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultapreanestesia',
            name='prueba_embarazo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Prueba Embarazo'),
        ),
        migrations.AddField(
            model_name='consultapreanestesia',
            name='tipiaje',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipiaje'),
        ),
        migrations.AddField(
            model_name='consultapreanestesia',
            name='uroanalisis',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Uroanálisis'),
        ),
        migrations.CreateModel(
            name='HistoricalConsumoCirugia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad_uso', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_uso')),
                ('venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='venta')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('precio_costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio_costo_unitario')),
                ('hora', models.TimeField(default=appcc58.models.get_current_time, null=True, verbose_name='Hora asignacion')),
                ('hora_uso', models.TimeField(null=True, verbose_name='Hora Uso')),
                ('fecha_act', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha Actualizacion')),
                ('cantidad_real_usada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_real_usada')),
                ('farmacia', models.BooleanField(default=False, verbose_name='Pendiente Farmacia')),
                ('nota', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nota Entrega')),
                ('diferencia', models.IntegerField(default=0, verbose_name='Diferencia cantidades')),
                ('disponible', models.PositiveBigIntegerField(default=0, verbose_name='Disponible')),
                ('conciliada', models.BooleanField(default=False, verbose_name='Conciliada Farmacia')),
                ('obligatoria', models.BooleanField(default=False, verbose_name='Obligatoria')),
                ('advertencia', models.BooleanField(default=False, verbose_name='advertencia')),
                ('compuesto', models.CharField(choices=[('1', 'Ninguno'), ('2', 'Compuesto'), ('3', 'Suministro Bomba')], default='1', max_length=1, verbose_name='compuesto')),
                ('seleccionado', models.BooleanField(default=False, verbose_name='seleccionado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atencion_cortesia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia')),
                ('atencion_inmediata', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.atencioninmediata', verbose_name='atencion_inmediata')),
                ('baremo_cobro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.detallebaremo', verbose_name='baremo_cobro')),
                ('cirugia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.cirugia', verbose_name='Cirugia')),
                ('consumo', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.lugarconsumo', verbose_name='Lugar Afectado')),
                ('deposito', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.deposito', verbose_name='Deposito Afectado')),
                ('detalle_presupuesto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.detallepresupuesto', verbose_name='DetallePresupuesto')),
                ('entregado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.medico', verbose_name='entregado_medico')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.inventario', verbose_name='Inventario')),
                ('preingreso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.preingreso', verbose_name='preingreso')),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.medico', verbose_name='solicitante_medico')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical ConsumoCirugia',
                'verbose_name_plural': 'historical Consumo de Cirugia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInventarioDescarga',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad')),
                ('nota', models.CharField(blank=True, max_length=250, null=True, verbose_name='Notas')),
                ('fecha_act', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha Actualizacion')),
                ('descargamanual', models.CharField(blank=True, max_length=10, null=True, verbose_name='descargamanual')),
                ('cantidad_traslado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad_traslado')),
                ('reciclado', models.BooleanField(default=False, verbose_name='reciclado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atencion_cortesia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.atencioninmediatacortesia', verbose_name='atencion_cortesia')),
                ('atencion_inmediata', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.atencioninmediata', verbose_name='atencion_inmediata')),
                ('cirugia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.cirugia', verbose_name='Cirugia ID')),
                ('consumocirugia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.consumocirugia', verbose_name='consumocirugia')),
                ('deposito', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.deposito', verbose_name='Deposito Salida')),
                ('depositoentrada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.deposito', verbose_name='Deposito Entrada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.inventario', verbose_name='Inventario')),
                ('materiaprima', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.materiaprimainventario', verbose_name='materiaprima')),
                ('persona', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.medico', verbose_name='Persona entrega')),
                ('preingreso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.preingreso', verbose_name='preingreso')),
                ('tipodescarga', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appcc58.tipodescarga', verbose_name='TipoDescarga')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical InventarioDescarga',
                'verbose_name_plural': 'historical Movimiento de Inventario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
