# Generated by Django 5.0.14 on 2026-06-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0138_consultapreanestesia_prueba_embarazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultapreanestesia',
            name='eco_abdominopelvico',
            field=models.BooleanField(default=False, verbose_name='Eco Abdominopelvico'),
        ),
        migrations.AddField(
            model_name='consultapreanestesia',
            name='eco_mamario',
            field=models.BooleanField(default=False, verbose_name='Eco Mamario'),
        ),
        migrations.AddField(
            model_name='consultapreanestesia',
            name='eco_pared_abdominal',
            field=models.BooleanField(default=False, verbose_name='Eco Pared Abdominal'),
        ),
        migrations.AddField(
            model_name='consultapreanestesia',
            name='otros_examenes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otros Examenes'),
        ),
    ]
