# Generated by Django 5.0.14 on 2026-06-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0138_tempfecha_caso_cerrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultapreanestesia',
            name='hiv',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='hiv'),
        ),
        migrations.AlterField(
            model_name='consultapreanestesia',
            name='vdrl',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='vdrl'),
        ),
    ]
