# Generated by Django 5.0.14 on 2026-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0139_consultapreanestesia_eco_abdominopelvico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tipo'),
        ),
    ]
