# Generated by Django 5.0.14 on 2026-06-25 14:41

import appcc58.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0140_respuestaevaluacion_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentocirugia',
            options={},
        ),
        migrations.AlterField(
            model_name='documentocirugia',
            name='archivo',
            field=models.FileField(upload_to=appcc58.models.ruta_cirugia, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='documentocirugia',
            name='cargado',
            field=models.ImageField(blank=True, null=True, upload_to='cirugia/', verbose_name='cargado'),
        ),
        migrations.AlterField(
            model_name='respuestaevaluacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='tipo'),
        ),
    ]
