# Generated by Django 5.0.14 on 2026-06-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0140_alter_consultapreanestesia_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='detalle_origen_prefactura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='detalle_origen_prefactura'),
        ),
    ]
