# Generated by Django 5.0.14 on 2026-07-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0141_alter_documentocirugia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleHospitalCorteCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, verbose_name='activo')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appcc58.detallebaremo')),
            ],
            options={
                'verbose_name': 'DetalleHospitalCorteCuenta',
                'verbose_name_plural': 'DetalleHospitalCorteCuentas',
            },
        ),
    ]
