# Generated by Django 5.0.14 on 2026-07-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0143_detallehospitalcortecuenta_fecha_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditoctapagar',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creacion'),
        ),
    ]
