# Generated by Django 5.0.14 on 2026-06-10 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0145_alter_transaccion_cuentapagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cuentapagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.facturaproveedor', verbose_name='Factura proveedor'),
        ),
    ]
