# Generated by Django 5.0.14 on 2026-06-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcc58', '0151_historianotacreditocp_fecha_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historianotacreditocp',
            name='factura',
        ),
        migrations.AddField(
            model_name='historianotacreditocp',
            name='detallefactura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcc58.detallefacturaproveedor', verbose_name='detallefactura'),
        ),
    ]
